"""
models/model_router.py
-----------------------
Routes generation tasks to the correct model based on complexity score.

FULL 8-MODEL FALLBACK CHAIN:

  TIER 1 — Azure OpenAI (PRIMARY — Microsoft stack — hackathon mandatory)
    1. gpt-4o          Complexity 8-10  Best quality
    2. phi-4           Complexity 4-7   Balanced speed + quality
    3. gpt-4o-mini     Complexity 1-3   Fast + cheap

  TIER 2 — Free models (fallback when Azure quota exhausted)
    4. Groq Llama 3.3-70b    Fastest free inference
    5. Groq Mixtral 8x7b     Strong reasoning
    6. Google Gemini Flash   Large context (1M tokens)
    7. Cohere Command-R      Structured JSON specialist

  TIER 3 — Last resort
    8. Mistral 7B (OpenRouter)  Lightweight, always available
    9. Cached template          System NEVER crashes

Usage:
    from models.model_router import ModelRouter
    router = ModelRouter()
    result = router.complete(system_prompt, user_prompt, complexity=7)
"""

import logging
import os
from typing import Any

from models.azure_openai import AzureOpenAIModel, AzureOpenAIError
from models.phi4 import Phi4Model, Phi4Error
from models.free_models import (
    GroqLlamaModel, GroqMixtralModel, GeminiFlashModel,
    CohereCommandRModel, MistralOpenRouterModel, FreeModelError
)

logger = logging.getLogger(__name__)

# Cached template responses — used when ALL 8 models fail
_TEMPLATE_RESPONSES: dict[str, str] = {
    "dockerfile": (
        "FROM python:3.11-slim\n"
        "WORKDIR /app\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "COPY . .\n"
        "EXPOSE 8000\n"
        "HEALTHCHECK CMD curl -f http://localhost:8000/health || exit 1\n"
        'CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
    ),
    "ci": (
        "name: CI\n"
        "on: [push, pull_request]\n"
        "jobs:\n"
        "  test:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-python@v5\n"
        "        with: {python-version: '3.11'}\n"
        "      - run: pip install -r requirements.txt\n"
        "      - run: pytest tests/\n"
    ),
    "default": "# Generated by Swarm Factory\n",
}


class ModelRouter:
    """
    8-model router with full Azure-primary + free-model fallback chain.

    Azure models are ALWAYS tried first (hackathon compliance).
    Free models are fallback only — used when Azure quota is exhausted.
    This makes the system resilient while keeping Microsoft stack as core.

    Complexity routing:
      1-3  → gpt-4o-mini  (fast, cheap)
      4-7  → phi-4        (balanced)
      8-10 → gpt-4o       (best quality)
    """

    def __init__(self) -> None:
        # Lazy-init — models created on first use
        self._gpt4o:   AzureOpenAIModel | None = None
        self._phi4:    Phi4Model | None         = None
        self._mini:    AzureOpenAIModel | None  = None
        self._llama:   GroqLlamaModel | None    = None
        self._mixtral: GroqMixtralModel | None  = None
        self._gemini:  GeminiFlashModel | None  = None
        self._cohere:  CohereCommandRModel | None = None
        self._mistral: MistralOpenRouterModel | None = None

    def complete(
        self,
        system_prompt: str,
        user_prompt: str,
        complexity: int,
        template_key: str = "default",
    ) -> str:
        """
        Route to best model for this complexity. Fall back through chain on failure.

        Args:
            system_prompt: System instruction for the LLM.
            user_prompt:   User message / task.
            complexity:    1-10 task difficulty score.
            template_key:  Key for cached fallback ("dockerfile", "ci", "default").

        Returns:
            Generated text string from whichever model succeeded.
        """
        complexity  = max(1, min(10, complexity))
        chain       = self._build_full_chain(complexity)

        for model_name, call in chain:
            try:
                logger.info("Trying model | model=%s | complexity=%d", model_name, complexity)
                result = call(system_prompt, user_prompt)
                logger.info("Model succeeded | model=%s", model_name)

                # Log which tier was used for observability
                tier = self._get_tier(model_name)
                if tier > 1:
                    logger.warning(
                        "Azure quota exhausted — used free model fallback | "
                        "model=%s | tier=%d", model_name, tier
                    )
                return result

            except (AzureOpenAIError, Phi4Error, FreeModelError, Exception) as exc:
                logger.warning("Model failed | model=%s | error=%s", model_name, str(exc)[:100])
                continue

        # All 8 models failed — return cached template (never crash)
        logger.error("All 8 models failed — returning cached template | key=%s", template_key)
        return _TEMPLATE_RESPONSES.get(template_key, _TEMPLATE_RESPONSES["default"])

    def _build_full_chain(self, complexity: int) -> list[tuple[str, Any]]:
        """
        Build ordered list of (model_name, callable) for given complexity.

        Azure models come first in every chain (hackathon requirement).
        Free models follow in order of speed/quality.
        """
        # Azure tier (always first — Microsoft stack mandatory)
        if complexity <= 3:
            azure_chain = [
                ("gpt-4o-mini [Azure]", self._get_mini().complete),
                ("phi-4 [Azure]",       self._get_phi4().complete),
                ("gpt-4o [Azure]",      self._get_gpt4o().complete),
            ]
        elif complexity <= 7:
            azure_chain = [
                ("phi-4 [Azure]",       self._get_phi4().complete),
                ("gpt-4o-mini [Azure]", self._get_mini().complete),
                ("gpt-4o [Azure]",      self._get_gpt4o().complete),
            ]
        else:
            azure_chain = [
                ("gpt-4o [Azure]",      self._get_gpt4o().complete),
                ("phi-4 [Azure]",       self._get_phi4().complete),
                ("gpt-4o-mini [Azure]", self._get_mini().complete),
            ]

        # Free tier fallback (used only if Azure exhausted)
        free_chain = [
            ("Groq Llama-3.3-70b [Free]",  self._get_llama().complete),
            ("Groq Mixtral-8x7b [Free]",   self._get_mixtral().complete),
            ("Gemini 1.5 Flash [Free]",    self._get_gemini().complete),
            ("Cohere Command-R [Free]",    self._get_cohere().complete),
            ("Mistral-7B OpenRouter [Free]", self._get_mistral().complete),
        ]

        return azure_chain + free_chain

    @staticmethod
    def _get_tier(model_name: str) -> int:
        return 1 if "[Azure]" in model_name else 2

    # ── Lazy getters ──────────────────────────────────────────────────────────

    def _get_gpt4o(self) -> AzureOpenAIModel:
        if self._gpt4o is None:
            self._gpt4o = AzureOpenAIModel(deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_GPT4O"])
        return self._gpt4o

    def _get_phi4(self) -> Phi4Model:
        if self._phi4 is None:
            self._phi4 = Phi4Model(deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_PHI4"])
        return self._phi4

    def _get_mini(self) -> AzureOpenAIModel:
        if self._mini is None:
            self._mini = AzureOpenAIModel(
                deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_MINI"],
                fallback_deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_MINI"],
            )
        return self._mini

    def _get_llama(self) -> GroqLlamaModel:
        if self._llama is None: self._llama = GroqLlamaModel()
        return self._llama

    def _get_mixtral(self) -> GroqMixtralModel:
        if self._mixtral is None: self._mixtral = GroqMixtralModel()
        return self._mixtral

    def _get_gemini(self) -> GeminiFlashModel:
        if self._gemini is None: self._gemini = GeminiFlashModel()
        return self._gemini

    def _get_cohere(self) -> CohereCommandRModel:
        if self._cohere is None: self._cohere = CohereCommandRModel()
        return self._cohere

    def _get_mistral(self) -> MistralOpenRouterModel:
        if self._mistral is None: self._mistral = MistralOpenRouterModel()
        return self._mistral
