"""
models/model_router.py
----------------------
Routes generation tasks to the correct AI model based on complexity score.

Routing table
-------------
Complexity 1-3  → gpt-4o-mini  (simple tasks: .gitignore, README)
Complexity 4-7  → phi-4        (mid tasks: Dockerfile, CI/CD YAML)
Complexity 8-10 → gpt-4o       (complex: architecture, multi-file infra)

Fallback chain: gpt-4o → phi-4 → gpt-4o-mini → cached template

Usage:
    from models.model_router import ModelRouter
"""

import logging
import os
from typing import Any

from models.azure_openai import AzureOpenAIModel, AzureOpenAIError
from models.phi4 import Phi4Model, Phi4Error

logger = logging.getLogger(__name__)

# Fallback responses when ALL models fail — keeps the pipeline alive.
_TEMPLATE_RESPONSES: dict[str, str] = {
    "dockerfile": (
        "FROM python:3.11-slim\n"
        "WORKDIR /app\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "COPY . .\n"
        "EXPOSE 8000\n"
        'HEALTHCHECK CMD curl -f http://localhost:8000/health || exit 1\n'
        'CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
    ),
    "ci": (
        "name: CI\n"
        "on: [push, pull_request]\n"
        "jobs:\n"
        "  test:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-python@v5\n"
        "        with: {python-version: '3.11'}\n"
        "      - run: pip install -r requirements.txt\n"
        "      - run: pytest tests/\n"
    ),
    "default": "# Generated by Swarm Factory fallback template\n",
}


class ModelRouter:
    """
    Selects the appropriate AI model for a task and manages the fallback chain.

    Complexity bands
    ----------------
    1-3  : gpt-4o-mini  — fast & cheap, sufficient for trivial generation
    4-7  : phi-4        — balanced speed + capability
    8-10 : gpt-4o       — full reasoning for complex infrastructure tasks

    If the primary model fails the router tries the next model in the chain.
    If all models fail it returns a cached template string so the pipeline
    never crashes completely.
    """

    def __init__(self) -> None:
        """Initialise lazy model instances (created on first use)."""
        self._gpt4o: AzureOpenAIModel | None = None
        self._phi4: Phi4Model | None = None
        self._mini: AzureOpenAIModel | None = None

    # ── public API ────────────────────────────────────────────────────────────

    def complete(
        self,
        system_prompt: str,
        user_prompt: str,
        complexity: int,
        template_key: str = "default",
    ) -> str:
        """
        Route a completion request to the correct model.

        Args:
            system_prompt: System message for the LLM.
            user_prompt: User message for the LLM.
            complexity: Integer 1-10 indicating task difficulty.
            template_key: Key into ``_TEMPLATE_RESPONSES`` used as last-resort
                fallback (e.g. "dockerfile", "ci", "default").

        Returns:
            Generated text from the selected model, or a cached template if
            all models fail.
        """
        complexity = max(1, min(10, complexity))
        chain = self._build_chain(complexity)

        for model_name, call in chain:
            try:
                logger.info(
                    "ModelRouter trying model",
                    extra={"model": model_name, "complexity": complexity},
                )
                result = call(system_prompt, user_prompt)
                logger.info(
                    "ModelRouter success",
                    extra={"model": model_name},
                )
                return result
            except (AzureOpenAIError, Phi4Error, Exception) as exc:
                logger.warning(
                    "ModelRouter model failed, trying next",
                    extra={"model": model_name, "error": str(exc)},
                )

        logger.error(
            "All models failed — returning cached template",
            extra={"template_key": template_key},
        )
        return _TEMPLATE_RESPONSES.get(template_key, _TEMPLATE_RESPONSES["default"])

    # ── internals ─────────────────────────────────────────────────────────────

    def _build_chain(
        self, complexity: int
    ) -> list[tuple[str, Any]]:
        """
        Build the ordered list of (name, callable) to try for this complexity.

        Args:
            complexity: Integer 1-10.

        Returns:
            Ordered list of (model_name, bound_complete_method) tuples.
        """
        if complexity <= 3:
            primary = ("gpt-4o-mini", self._get_mini().complete)
            return [
                primary,
                ("phi-4", self._get_phi4().complete),
                ("gpt-4o", lambda s, u: self._get_gpt4o().complete(s, u)),
            ]
        elif complexity <= 7:
            return [
                ("phi-4", self._get_phi4().complete),
                ("gpt-4o-mini", self._get_mini().complete),
                ("gpt-4o", lambda s, u: self._get_gpt4o().complete(s, u)),
            ]
        else:
            return [
                ("gpt-4o", lambda s, u: self._get_gpt4o().complete(s, u)),
                ("phi-4", self._get_phi4().complete),
                ("gpt-4o-mini", self._get_mini().complete),
            ]

    def _get_gpt4o(self) -> AzureOpenAIModel:
        """Lazy-init GPT-4o model."""
        if self._gpt4o is None:
            self._gpt4o = AzureOpenAIModel(
                deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_GPT4O"]
            )
        return self._gpt4o

    def _get_phi4(self) -> Phi4Model:
        """Lazy-init Phi-4 model."""
        if self._phi4 is None:
            self._phi4 = Phi4Model(
                deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_PHI4"]
            )
        return self._phi4

    def _get_mini(self) -> AzureOpenAIModel:
        """Lazy-init GPT-4o-mini model."""
        if self._mini is None:
            self._mini = AzureOpenAIModel(
                deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_MINI"],
                fallback_deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_MINI"],
            )
        return self._mini
