"""
models/model_router.py
-----------------------
Routes generation tasks to the correct Azure OpenAI model based on complexity score.

THREE-MODEL AZURE FALLBACK CHAIN:
  1. gpt-4o       Complexity 8-10  Best quality
  2. phi-4        Complexity 4-7   Balanced speed + quality
  3. gpt-4o-mini  Complexity 1-3   Fast + cheap

If all three Azure deployments fail, a cached template is returned so the
system never crashes. No external/free providers are used.

Usage:
    from models.model_router import ModelRouter
    router = ModelRouter()
    result = router.complete(system_prompt, user_prompt, complexity=7)
"""

import logging
import os
from typing import Any

from models.azure_openai import AzureOpenAIModel, AzureOpenAIError
from models.phi4 import Phi4Model, Phi4Error

logger = logging.getLogger(__name__)

# Cached template responses — used when all three Azure models fail
_TEMPLATE_RESPONSES: dict[str, str] = {
    "dockerfile": (
        "FROM python:3.11-slim\n"
        "WORKDIR /app\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "COPY . .\n"
        "EXPOSE 8000\n"
        "HEALTHCHECK CMD curl -f http://localhost:8000/health || exit 1\n"
        'CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
    ),
    "ci": (
        "name: CI\n"
        "on: [push, pull_request]\n"
        "jobs:\n"
        "  test:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-python@v5\n"
        "        with: {python-version: '3.11'}\n"
        "      - run: pip install -r requirements.txt\n"
        "      - run: pytest tests/\n"
    ),
    "default": "# Generated by Swarm Factory\n",
}


class ModelRouter:
    """
    Azure-only router with three-model fallback chain.

    All inference goes through Azure OpenAI — no external providers.
    Complexity routing:
      1-3  → gpt-4o-mini  (fast, cheap)
      4-7  → phi-4        (balanced)
      8-10 → gpt-4o       (best quality)
    """

    def __init__(self) -> None:
        self._gpt4o: AzureOpenAIModel | None = None
        self._phi4:  Phi4Model | None         = None
        self._mini:  AzureOpenAIModel | None  = None

    def complete(
        self,
        system_prompt: str,
        user_prompt: str,
        complexity: int,
        template_key: str = "default",
    ) -> str:
        """
        Route to the best Azure model for this complexity.
        Falls back through the three-model chain on failure.
        """
        complexity = max(1, min(10, complexity))
        chain      = self._build_chain(complexity)

        for model_name, call in chain:
            try:
                logger.info("Trying model | model=%s | complexity=%d", model_name, complexity)
                result = call(system_prompt, user_prompt)
                logger.info("Model succeeded | model=%s", model_name)
                return result
            except (AzureOpenAIError, Phi4Error, Exception) as exc:
                logger.warning("Model failed | model=%s | error=%s", model_name, str(exc)[:100])
                continue

        logger.error("All Azure models failed — returning cached template | key=%s", template_key)
        return _TEMPLATE_RESPONSES.get(template_key, _TEMPLATE_RESPONSES["default"])

    def _build_chain(self, complexity: int) -> list[tuple[str, Any]]:
        """Build ordered (model_name, callable) list for the given complexity."""
        if complexity <= 3:
            return [
                ("gpt-4o-mini [Azure]", self._get_mini().complete),
                ("phi-4 [Azure]",       self._get_phi4().complete),
                ("gpt-4o [Azure]",      self._get_gpt4o().complete),
            ]
        elif complexity <= 7:
            return [
                ("phi-4 [Azure]",       self._get_phi4().complete),
                ("gpt-4o-mini [Azure]", self._get_mini().complete),
                ("gpt-4o [Azure]",      self._get_gpt4o().complete),
            ]
        else:
            return [
                ("gpt-4o [Azure]",      self._get_gpt4o().complete),
                ("phi-4 [Azure]",       self._get_phi4().complete),
                ("gpt-4o-mini [Azure]", self._get_mini().complete),
            ]

    # ── Lazy getters ──────────────────────────────────────────────────────────

    def _get_gpt4o(self) -> AzureOpenAIModel:
        if self._gpt4o is None:
            self._gpt4o = AzureOpenAIModel(deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_GPT4O"])
        return self._gpt4o

    def _get_phi4(self) -> Phi4Model:
        if self._phi4 is None:
            self._phi4 = Phi4Model(deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_PHI4"])
        return self._phi4

    def _get_mini(self) -> AzureOpenAIModel:
        if self._mini is None:
            self._mini = AzureOpenAIModel(
                deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_MINI"],
                fallback_deployment=os.environ["AZURE_OPENAI_DEPLOYMENT_MINI"],
            )
        return self._mini
