"""
agents/devops_agent.py
----------------------
Agent 7 (DevOps) for Swarm Factory.

Takes the final merged codebase from MediatorAgent and makes it live:
  1. Generates Dockerfile, GitHub Actions CI workflow, and .gitignore via LLM.
  2. Writes all files to a temp directory.
  3. Creates a GitHub repo and pushes the code.
  4. Builds and pushes a Docker image to Azure Container Registry.
  5. Deploys the image to Azure Container Apps.

In dry_run=True mode, steps 3-5 are skipped so the agent can be tested
without real cloud credentials.

Importable as:
    from agents.devops_agent import DevOpsAgent, DeployOutput
"""

import logging
import os
import tempfile
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from models.model_router import ModelRouter
from prompts.devops import (
    dockerfile_prompt,
    ci_workflow_prompt,
    gitignore_prompt,
    readme_prompt,
)

logger = logging.getLogger(__name__)


# ── Output schema ─────────────────────────────────────────────────────────────

class DeployOutput(BaseModel):
    """
    Result produced by DevOpsAgent after a full deployment run.

    Attributes:
        github_url: HTTPS URL to the created GitHub repository.
        azure_url: Public HTTPS URL of the deployed Azure Container App.
        dockerfile_path: Relative path to the generated Dockerfile.
        ci_workflow_path: Relative path to the CI workflow YAML.
        deploy_success: True if GitHub push and Azure deploy both succeeded.
        image_uri: Full image URI pushed to the container registry.
        error: Human-readable error message when ``deploy_success`` is False.
    """

    github_url: str
    azure_url: str
    dockerfile_path: str
    ci_workflow_path: str
    deploy_success: bool
    image_uri: str
    error: str | None = None


# ── Agent ─────────────────────────────────────────────────────────────────────

class DevOpsAgent:
    """
    Agent 7: DevOps, containerisation, and cloud deployment.

    Orchestrates LLM-based generation of infrastructure files and the full
    GitHub → Docker → Azure deployment pipeline.

    Args:
        dry_run: When True, skip GitHub / Docker / Azure calls and return
            synthetic URLs.  Useful for unit testing.
        router: Optional pre-configured ModelRouter; created automatically if
            not provided.
    """

    def __init__(
        self,
        dry_run: bool = False,
        router: ModelRouter | None = None,
    ) -> None:
        """Initialise DevOpsAgent."""
        self.dry_run = dry_run
        self.router = router or ModelRouter()

    async def run(self, codebase: dict[str, Any]) -> DeployOutput:
        """
        Run the full DevOps pipeline for a generated codebase.

        Args:
            codebase: Dict matching the ``FinalCodebase`` schema from
                MediatorAgent.  Accepted keys: ``files``, ``test_files``,
                ``dependencies``, ``entry_point``, ``start_command``,
                ``test_command``, ``conflicts_resolved``, ``quality_score``.

        Returns:
            ``DeployOutput`` with deployment results.
        """
        logger.info("DevOpsAgent starting", extra={"dry_run": self.dry_run})

        # ── Normalise input ──────────────────────────────────────────────────
        files: dict[str, str] = codebase.get("files", {})
        test_files: dict[str, str] = codebase.get("test_files", {})
        dependencies: list[str] = codebase.get("dependencies", [])
        start_command: str = codebase.get("start_command", "python main.py")
        test_command: str = codebase.get("test_command", "pytest tests/")

        language, framework = _detect_language_framework(files, dependencies)
        app_name = _generate_app_name()

        # ── Generate infra files via LLM ─────────────────────────────────────
        logger.info(
            "Generating infrastructure files",
            extra={"language": language, "framework": framework},
        )
        dockerfile_content = self._generate_dockerfile(
            language, framework, start_command, dependencies
        )
        ci_content = self._generate_ci_workflow(language, test_command)
        gitignore_content = self._generate_gitignore(language, framework)
        readme_content = self._generate_readme(
            f"A {language} {framework} application generated by Swarm Factory.",
            start_command,
            test_command,
            dependencies,
        )

        # ── Write everything to a temp directory ─────────────────────────────
        with tempfile.TemporaryDirectory(prefix="swarm-factory-") as tmpdir:
            tmp = Path(tmpdir)

            _write_project_files(tmp, files)
            _write_project_files(tmp, test_files)
            _write_requirements_txt(tmp, dependencies)

            (tmp / "Dockerfile").write_text(dockerfile_content, encoding="utf-8")
            (tmp / ".gitignore").write_text(gitignore_content, encoding="utf-8")
            (tmp / "README.md").write_text(readme_content, encoding="utf-8")

            ci_dir = tmp / ".github" / "workflows"
            ci_dir.mkdir(parents=True, exist_ok=True)
            ci_file = ci_dir / "ci.yml"
            ci_file.write_text(ci_content, encoding="utf-8")

            logger.info(
                "Project files written",
                extra={"path": str(tmp), "file_count": len(list(tmp.rglob("*")))},
            )

            # ── Cloud deployment ─────────────────────────────────────────────
            if self.dry_run:
                return self._dry_run_output(app_name)

            return await self._deploy(
                tmp=tmp,
                app_name=app_name,
                dockerfile_content=dockerfile_content,
                ci_workflow_path=".github/workflows/ci.yml",
            )

    # ── LLM generation helpers ────────────────────────────────────────────────

    def _generate_dockerfile(
        self,
        language: str,
        framework: str,
        start_command: str,
        dependencies: list[str],
    ) -> str:
        """Generate a production Dockerfile using the model router."""
        sys_p, usr_p = dockerfile_prompt(language, framework, start_command, dependencies)
        return self.router.complete(sys_p, usr_p, complexity=5, template_key="dockerfile")

    def _generate_ci_workflow(self, language: str, test_command: str) -> str:
        """Generate a GitHub Actions CI workflow YAML."""
        sys_p, usr_p = ci_workflow_prompt(language, test_command)
        return self.router.complete(sys_p, usr_p, complexity=5, template_key="ci")

    def _generate_gitignore(self, language: str, framework: str) -> str:
        """Generate a .gitignore appropriate for the tech stack."""
        sys_p, usr_p = gitignore_prompt(language, framework)
        return self.router.complete(sys_p, usr_p, complexity=2, template_key="default")

    def _generate_readme(
        self,
        description: str,
        start_command: str,
        test_command: str,
        dependencies: list[str],
    ) -> str:
        """Generate a minimal README.md."""
        sys_p, usr_p = readme_prompt(description, start_command, test_command, dependencies)
        return self.router.complete(sys_p, usr_p, complexity=1, template_key="default")

    # ── Deployment ────────────────────────────────────────────────────────────

    async def _deploy(
        self,
        tmp: Path,
        app_name: str,
        dockerfile_content: str,
        ci_workflow_path: str,
    ) -> DeployOutput:
        """
        Run the GitHub → Docker → Azure deployment pipeline.

        Args:
            tmp: Temp directory containing all project files.
            app_name: Unique name for the GitHub repo and Azure app.
            dockerfile_content: Generated Dockerfile content (used in output).
            ci_workflow_path: Relative path to the CI workflow.

        Returns:
            ``DeployOutput`` with real URLs, or a failure output on error.
        """
        # Import here to allow dry_run to skip these imports entirely
        from tools.git_ops import create_repo_and_push, GitOpsError
        from tools.docker_builder import build_and_push, DockerBuildError
        from tools.azure_deploy import deploy_to_container_apps, AzureDeployError

        registry = os.environ.get("AZURE_CONTAINER_REGISTRY", "")
        resource_group = os.environ.get("AZURE_RESOURCE_GROUP", "swarm-factory-rg")

        github_url = ""
        image_uri = ""
        azure_url = ""

        # Step 1: GitHub
        try:
            logger.info("Pushing to GitHub", extra={"app": app_name})
            github_url = create_repo_and_push(
                local_path=str(tmp),
                repo_name=app_name,
                description="Generated by Swarm Factory",
            )
            logger.info("GitHub push complete", extra={"url": github_url})
        except GitOpsError as exc:
            logger.error("GitHub push failed", extra={"error": str(exc)})
            return DeployOutput(
                github_url="",
                azure_url="",
                dockerfile_path="Dockerfile",
                ci_workflow_path=ci_workflow_path,
                deploy_success=False,
                image_uri="",
                error=f"GitHub push failed: {exc}",
            )

        # Step 2: Docker build & push
        try:
            logger.info("Building and pushing Docker image", extra={"app": app_name})
            image_uri = build_and_push(
                project_path=str(tmp),
                image_tag=app_name,
                registry=registry,
            )
            logger.info("Docker push complete", extra={"image_uri": image_uri})
        except DockerBuildError as exc:
            logger.error("Docker build failed", extra={"error": str(exc)})
            return DeployOutput(
                github_url=github_url,
                azure_url="",
                dockerfile_path="Dockerfile",
                ci_workflow_path=ci_workflow_path,
                deploy_success=False,
                image_uri="",
                error=f"Docker build/push failed: {exc}",
            )

        # Step 3: Azure deploy
        try:
            logger.info("Deploying to Azure", extra={"app": app_name})
            azure_url = deploy_to_container_apps(
                image_uri=image_uri,
                app_name=app_name,
                resource_group=resource_group,
            )
            logger.info("Azure deployment complete", extra={"url": azure_url})
        except AzureDeployError as exc:
            logger.error("Azure deploy failed", extra={"error": str(exc)})
            return DeployOutput(
                github_url=github_url,
                azure_url="",
                dockerfile_path="Dockerfile",
                ci_workflow_path=ci_workflow_path,
                deploy_success=False,
                image_uri=image_uri,
                error=f"Azure deployment failed: {exc}",
            )

        return DeployOutput(
            github_url=github_url,
            azure_url=azure_url,
            dockerfile_path="Dockerfile",
            ci_workflow_path=ci_workflow_path,
            deploy_success=True,
            image_uri=image_uri,
            error=None,
        )

    def _dry_run_output(self, app_name: str) -> DeployOutput:
        """Return a synthetic DeployOutput for dry_run mode."""
        logger.info("Dry run — skipping cloud deployment", extra={"app": app_name})
        return DeployOutput(
            github_url=f"https://github.com/swarm-factory/{app_name}",
            azure_url=f"https://{app_name}.azurecontainerapps.io",
            dockerfile_path="Dockerfile",
            ci_workflow_path=".github/workflows/ci.yml",
            deploy_success=True,
            image_uri=f"swarmfactory.azurecr.io/{app_name}:latest",
            error=None,
        )


# ── Utilities ─────────────────────────────────────────────────────────────────

def _detect_language_framework(
    files: dict[str, str], dependencies: list[str]
) -> tuple[str, str]:
    """
    Heuristically detect the primary language and framework.

    Args:
        files: Project source files.
        dependencies: Dependency list.

    Returns:
        Tuple of (language, framework), defaulting to ("Python", "FastAPI").
    """
    deps_lower = " ".join(dependencies).lower()
    files_lower = " ".join(files.keys()).lower()

    language = "Python"
    framework = "FastAPI"

    if "fastapi" in deps_lower:
        framework = "FastAPI"
    elif "flask" in deps_lower:
        framework = "Flask"
    elif "django" in deps_lower:
        framework = "Django"
    elif "express" in files_lower or "node" in files_lower:
        language = "Node.js"
        framework = "Express"

    return language, framework


def _generate_app_name() -> str:
    """
    Generate a unique lowercase app name with a timestamp suffix.

    Returns:
        App name string, e.g. ``"swarm-app-20240115-143022"``.
    """
    import time
    ts = time.strftime("%Y%m%d-%H%M%S")
    return f"swarm-app-{ts}"


def _write_project_files(base: Path, files: dict[str, str]) -> None:
    """
    Write a dict of {relative_path: content} to the filesystem.

    Args:
        base: Base directory to write into.
        files: Mapping of relative path → file content.
    """
    for rel_path, content in files.items():
        dest = base / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")


def _write_requirements_txt(base: Path, dependencies: list[str]) -> None:
    """
    Write a ``requirements.txt`` from a dependency list.

    Args:
        base: Base directory.
        dependencies: List of dependency strings.
    """
    req_file = base / "requirements.txt"
    if not req_file.exists():  # don't overwrite if already provided
        req_file.write_text("\n".join(dependencies) + "\n", encoding="utf-8")
